cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'
tap 'homebrew/cask-fonts'
tap 'heroku/brew'


brew 'p7zip'
brew 'coreutils'
brew 'curl'
brew 'docker'
brew 'grc'
brew 'heroku'
brew 'imagemagick'
brew 'jp2a'
brew 'mongodb'
brew 'nvm'
brew 'jq'
brew 'openssl'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'scriptcs'
brew 'spaceman-diff'
brew 'spark'
brew 'telnet'
brew 'unrar'
brew 'wget'

cask 'docker'
cask 'font-fira-code'
cask 'fork'
cask 'firefox'
cask 'google-chrome'
cask 'java'
cask 'pgAdmin4'
cask 'postman'
cask 'robo-3t'
cask 'slack'
cask 'spectacle'
cask 'transmission'
cask 'visual-studio-code'
